[package]
name = "basic-merkle-tree-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
sha3 = { version = "0.10.8", optional = true }
tiny-keccak = { version = "2.0.2", features = ["keccak"], optional = true }

[features]
default = ["sha3"]
sha3 = ["dep:sha3"]
keccak = ["dep:tiny-keccak"]
